name: update-flake-lock
on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *" # 5 am UTC

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
      - name: The Determinate Nix Installer
        uses: DeterminateSystems/nix-installer-action@v8    
      - name: Update Nix Flake Lock
        uses: DeterminateSystems/update-flake-lock@v20    
        with:
          pr-title: "Update flake.lock"
